#!/usr/bin/env python3
import sys
import math
import json
import subprocess

import tabulate


gpu_stat = '~/.local/bin/gpustat'


def fetch(server):
    return subprocess.Popen(
        ['ssh', server, gpu_stat, '--json'],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


def fetch_all(servers):
    procs = {}
    results = {}
    for s in servers:
        procs[s] = fetch(s)
    for s, p in procs.items():
        try:
            print(s)
            stdout, stderr = p.communicate(timeout=10)
        except subprocess.TimeoutExpired as e:
            p.kill()
            results[s] = {'error': e}
            continue
        if p.returncode:
            results[s] = {
                'error': p.returncode,
                'stdout': stdout,
                'stderr': stderr,
            }
        else:
            results[s] = json.loads(stdout)
    return results


def gpu_name(name):
    if 'V100' in name:
        return 'v100'
    if 'A100' in name:
        return 'a100'
    if '3080 Ti' in name:
        return '3080ti'
    if '3090' in name:
        return '3090'
    return '?'


def unit(value):
    if value < 1024:
        return '0MB'
    units = 'MGTP'
    base = math.floor(math.log(value, 1024))
    value /= math.pow(1024, base)
    return f'{value:5.2f}{units[base]}B'


def format_processes(procs):
    users = set(p['username'] for p in procs)
    text = []
    for u in users:
        m = sum(p['gpu_memory_usage'] for p in procs if p['username'] == u)
        text.append(f'{u}({unit(m).strip()})')
    return ', '.join(text)


def format_table(results):
    lines = []
    for server, server_result in results.items():
        if 'error' in server_result:
            # error = stderr.decode().splitlines()[-1]
            print('-' * 40)
            print(f'{server}: error code {server_result["error"]}.')
            print(server_result.get('stdout'))
            print(server_result.get('stderr'))
            print('-' * 40)
            # lines.append([server, 'error'])
            continue
        for gpu in server_result['gpus']:
            line = [
                f'{server}.{gpu["index"]}',
                gpu_name(gpu["name"]),
                f'{gpu["utilization.gpu"]}%',
                f'{unit(gpu["memory.used"])}',
                f'{unit(gpu["memory.total"])}',
                format_processes(gpu["processes"])]
            lines.append(line)
    return lines


def main():
    servers = sys.argv[1:]
    if not servers:
        print('No servers specified.')
        sys.exit(-1)
    results = fetch_all(servers)
    table = format_table(results)
    if not table:
        return
    headers = ('Server', 'GPU', 'Usage', 'Used', 'Total', 'Users')
    colalign = ('right', 'left') + ('right', ) * 3 + ('left', )
    table = tabulate.tabulate(table, headers=headers, colalign=colalign)
    print(table)


if __name__ == '__main__':
    main()

